import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PartnerCTA from "@/components/cfa/PartnerCTA";

export const metadata: Metadata = { title: "Fractional Leadership Placements | Consult For Africa", description: "Part-time C-suite executives for hospitals that need senior leadership without full-time cost. Board-ready professionals with performance-linked terms.", keywords: ["fractional leadership healthcare", "part-time CEO hospital Africa", "fractional executive placement Nigeria", "hospital C-suite placement", "healthcare leadership on demand"], openGraph: { title: "Fractional Leadership Placements | Consult For Africa", description: "Part-time C-suite executives for African hospitals.", type: "website", images: ["/og-image.jpg"] } };

const features = ["2-3 days/week on-site or hybrid", "Board-ready healthcare executives", "Performance-linked terms", "Optional permanent hire conversion"];
const phases = [
  { num: "01", name: "Leadership Assessment", weeks: "Weeks 1 to 2", desc: "Assess the leadership gap, define the mandate, agree performance metrics, and determine the right executive profile.", deliverables: ["Leadership gap analysis", "Mandate brief", "Executive profile specification"] },
  { num: "02", name: "Executive Matching", weeks: "Weeks 2 to 4", desc: "Identify the right leader from our network. Board interviews, reference checks, and terms negotiation.", deliverables: ["Candidate shortlist", "Board interviews", "Engagement terms"] },
  { num: "03", name: "Embedded Leadership", weeks: "Months 1 to 18", desc: "Executive works part-time in the C-suite role. Drives strategy, builds team, and delivers against mandate objectives.", deliverables: ["Monthly board updates", "Quarterly performance reviews", "Team development reports"] },
  { num: "04", name: "Transition Planning", weeks: "Final quarter", desc: "Either convert to permanent hire or structured exit with successor development and full knowledge transfer.", deliverables: ["Successor development plan", "Transition roadmap", "Knowledge transfer documentation"] },
];
const qualifies = ["Hospitals that cannot afford or justify a full-time C-suite hire", "Organisations needing experienced leadership for a specific transformation", "Facilities where the founder needs a professional operator alongside them", "Boards wanting to test an executive before committing to permanent hire", "Investor groups needing professional management across a portfolio"];

export default function FractionalPage() {
  return (
    <main>
      <section className="relative overflow-hidden text-white" style={{ paddingTop: "5rem", minHeight: "60svh" }}><div className="absolute inset-0" style={{ background: "#06090f" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 70% 80% at 80% 40%, rgba(20,130,200,0.15) 0%, rgba(12,70,130,0.06) 55%, transparent 70%)" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 40% 50% at 20% 10%, rgba(201,168,76,0.1) 0%, transparent 60%)" }} /><div className="absolute inset-0 pointer-events-none opacity-[0.036]" style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`, backgroundSize: "180px" }} />
        <div className="relative max-w-7xl mx-auto px-6 py-24 md:py-32">
          <p className="mb-6 text-xs font-medium uppercase tracking-[0.22em]" style={{ color: "#D4AF37" }}>C4A Engagement Model</p>
          <h1 className="font-semibold leading-[1.1] tracking-tight text-white max-w-3xl" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)" }}>Fractional<br /><span style={{ color: "rgba(255,255,255,0.65)" }}>Leadership Placements</span></h1>
          <div className="mt-6 w-12 h-[2px]" style={{ background: "#D4AF37" }} />
          <p className="mt-6 max-w-2xl leading-relaxed" style={{ fontSize: "clamp(1rem,1.5vw,1.1rem)", color: "rgba(255,255,255,0.65)" }}>Part-time C-suite executives for hospitals that need senior leadership without full-time cost. Board-ready professionals, performance-linked terms, optional conversion to permanent hire.</p>
          <div className="mt-4 inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs" style={{ background: "rgba(212,175,55,0.12)", border: "1px solid rgba(212,175,55,0.35)", color: "#D4AF37" }}>Typical duration: 6 to 18 months</div>
          <div className="mt-8 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Start a Conversation <ArrowRight size={15} /></Link><Link href="/solutions" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.8)" }}>All Solutions</Link></div>
        </div>
      </section>
      <section className="py-16" style={{ background: "linear-gradient(135deg, #0B3C5D 0%, #0e4a75 100%)" }}><div className="max-w-4xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-5">{features.map((f) => (<div key={f} className="glass-card p-6 text-center"><p className="text-white text-sm font-medium">{f}</p></div>))}</div></section>
      <section className="py-24 px-6" style={{ background: "linear-gradient(145deg, #0a1e32 0%, #112e4a 100%)" }}><div className="max-w-5xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-white/50 mb-3">How It Works</p><h2 className="text-2xl md:text-3xl font-semibold text-white mb-14">The Fractional Leadership Process</h2><div className="space-y-5">{phases.map((phase) => (<div key={phase.num} className="glass-card p-7 grid md:grid-cols-[200px_1fr] gap-6"><div><div className="inline-flex items-center justify-center w-10 h-10 rounded-full text-xs font-bold mb-3" style={{ background: "rgba(212,175,55,0.12)", border: "1px solid rgba(212,175,55,0.35)", color: "#D4AF37" }}>{phase.num}</div><p className="font-semibold text-white text-base mb-1">{phase.name}</p><p className="text-xs" style={{ color: "#D4AF37" }}>{phase.weeks}</p></div><div><p className="text-white/70 text-sm leading-relaxed mb-4">{phase.desc}</p><div className="flex flex-wrap gap-2">{phase.deliverables.map((d) => (<span key={d} className="px-3 py-1 rounded-full text-xs" style={{ background: "rgba(255,255,255,0.07)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.1)" }}>{d}</span>))}</div></div></div>))}</div></div></section>
      <section className="py-20 px-6" style={{ background: "#ffffff" }}><div className="max-w-4xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-[#0B3C5D]/50 mb-3">Who This Is For</p><h2 className="text-2xl md:text-3xl font-semibold text-gray-900 mb-10">The Right Fit</h2><div className="space-y-3">{qualifies.map((q) => (<div key={q} className="flex items-center gap-4 p-4 rounded-xl" style={{ border: "1px solid #e5eaf0" }}><div className="w-2 h-2 rounded-full shrink-0" style={{ background: "#D4AF37" }} /><span className="text-sm text-gray-700">{q}</span></div>))}</div><div className="mt-12 rounded-2xl p-8" style={{ background: "#0F2744" }}><p className="text-xs font-semibold uppercase tracking-[0.15em] mb-2" style={{ color: "#D4AF37" }}>Start with a Conversation</p><h3 className="text-xl font-semibold text-white mb-3">Need a C-suite leader without the full-time commitment?</h3><p className="text-white/60 text-sm mb-6 max-w-lg">We will match you with an executive who fits your institution, your culture, and your mandate.</p><Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Find Your Leader <ArrowRight size={14} /></Link></div></div></section>
      <PartnerCTA />
    </main>
  );
}
