import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PartnerCTA from "@/components/cfa/PartnerCTA";

export const metadata: Metadata = { title: "Hospital Transformation Partnerships | Consult For Africa", description: "Equity-backed operational turnarounds for underperforming healthcare facilities. Consult For Africa takes operational control and shares in the upside.", keywords: ["hospital turnaround Africa", "healthcare transformation Nigeria", "equity-backed hospital management", "underperforming hospital recovery", "operational turnaround healthcare"], openGraph: { title: "Hospital Transformation Partnerships | Consult For Africa", description: "Equity-backed operational turnarounds for underperforming healthcare facilities.", type: "website", images: ["/og-image.jpg"] } };

const features = ["Equity-aligned incentives", "Full operational control", "KPI-driven performance", "Structured exit with defined returns"];
const phases = [
  { num: "01", name: "Diagnostic & Valuation", weeks: "Months 1 to 2", desc: "Full operational and financial assessment, entry valuation, deal structuring. We understand the asset before we commit.", deliverables: ["Operational diagnostic", "Financial model", "Entry valuation and term sheet"] },
  { num: "02", name: "Management Takeover", weeks: "Months 2 to 6", desc: "Consult For Africa assumes operational control, installs management team, and begins executing the turnaround plan.", deliverables: ["Management team deployment", "100-day plan", "Governance restructuring"] },
  { num: "03", name: "Performance Transformation", weeks: "Months 6 to 36", desc: "Systematic improvement of operations, revenue, quality, and governance. Monthly KPI tracking and quarterly board reporting.", deliverables: ["Monthly KPI dashboards", "Revenue growth initiatives", "Quality improvement programmes"] },
  { num: "04", name: "Exit & Value Realisation", weeks: "Months 36 to 60", desc: "Structured exit with defined return targets. Option for continued partnership, management buyout, or third-party sale.", deliverables: ["Exit readiness assessment", "Value realisation report", "Transition or continuation plan"] },
];
const qualifies = ["Underperforming hospitals where consulting alone is not enough", "Facility owners willing to share equity for guaranteed operational improvement", "Investor groups seeking operating partners for healthcare assets", "Mission hospitals needing commercial sustainability without losing their mission", "Hospital chains with individual facilities dragging down group performance"];

export default function TransformationPage() {
  return (
    <main>
      <section className="relative overflow-hidden text-white" style={{ paddingTop: "5rem", minHeight: "60svh" }}><div className="absolute inset-0" style={{ background: "#06090f" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 70% 80% at 80% 40%, rgba(20,130,200,0.15) 0%, rgba(12,70,130,0.06) 55%, transparent 70%)" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 40% 50% at 20% 10%, rgba(201,168,76,0.1) 0%, transparent 60%)" }} /><div className="absolute inset-0 pointer-events-none opacity-[0.036]" style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`, backgroundSize: "180px" }} />
        <div className="relative max-w-7xl mx-auto px-6 py-24 md:py-32">
          <p className="mb-6 text-xs font-medium uppercase tracking-[0.22em]" style={{ color: "#D4AF37" }}>C4AEngagement Model</p>
          <h1 className="font-semibold leading-[1.1] tracking-tight text-white max-w-3xl" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)" }}>Hospital<br /><span style={{ color: "rgba(255,255,255,0.65)" }}>Transformation Partnerships</span></h1>
          <div className="mt-6 w-12 h-[2px]" style={{ background: "#D4AF37" }} />
          <p className="mt-6 max-w-2xl leading-relaxed" style={{ fontSize: "clamp(1rem,1.5vw,1.1rem)", color: "rgba(255,255,255,0.65)" }}>Equity-backed operational turnarounds for underperforming healthcare facilities. We take operational control, invest our expertise, and share in the upside.</p>
          <div className="mt-4 inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-xs" style={{ background: "rgba(212,175,55,0.12)", border: "1px solid rgba(212,175,55,0.35)", color: "#D4AF37" }}>Typical duration: 24 to 60 months</div>
          <div className="mt-8 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Start a Conversation <ArrowRight size={15} /></Link><Link href="/solutions" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.8)" }}>All Solutions</Link></div>
        </div>
      </section>
      <section className="py-16" style={{ background: "linear-gradient(135deg, #0B3C5D 0%, #0e4a75 100%)" }}><div className="max-w-4xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-5">{features.map((f) => (<div key={f} className="glass-card p-6 text-center"><p className="text-white text-sm font-medium">{f}</p></div>))}</div></section>
      <section className="py-24 px-6" style={{ background: "linear-gradient(145deg, #0a1e32 0%, #112e4a 100%)" }}><div className="max-w-5xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-white/50 mb-3">How It Works</p><h2 className="text-2xl md:text-3xl font-semibold text-white mb-14">The Transformation Partnership Process</h2><div className="space-y-5">{phases.map((phase) => (<div key={phase.num} className="glass-card p-7 grid md:grid-cols-[200px_1fr] gap-6"><div><div className="inline-flex items-center justify-center w-10 h-10 rounded-full text-xs font-bold mb-3" style={{ background: "rgba(212,175,55,0.12)", border: "1px solid rgba(212,175,55,0.35)", color: "#D4AF37" }}>{phase.num}</div><p className="font-semibold text-white text-base mb-1">{phase.name}</p><p className="text-xs" style={{ color: "#D4AF37" }}>{phase.weeks}</p></div><div><p className="text-white/70 text-sm leading-relaxed mb-4">{phase.desc}</p><div className="flex flex-wrap gap-2">{phase.deliverables.map((d) => (<span key={d} className="px-3 py-1 rounded-full text-xs" style={{ background: "rgba(255,255,255,0.07)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.1)" }}>{d}</span>))}</div></div></div>))}</div></div></section>
      <section className="py-20 px-6" style={{ background: "#ffffff" }}><div className="max-w-4xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-[#0B3C5D]/50 mb-3">Who This Is For</p><h2 className="text-2xl md:text-3xl font-semibold text-gray-900 mb-10">The Right Fit</h2><div className="space-y-3">{qualifies.map((q) => (<div key={q} className="flex items-center gap-4 p-4 rounded-xl" style={{ border: "1px solid #e5eaf0" }}><div className="w-2 h-2 rounded-full shrink-0" style={{ background: "#D4AF37" }} /><span className="text-sm text-gray-700">{q}</span></div>))}</div><div className="mt-12 rounded-2xl p-8" style={{ background: "#0F2744" }}><p className="text-xs font-semibold uppercase tracking-[0.15em] mb-2" style={{ color: "#D4AF37" }}>Start with a Conversation</p><h3 className="text-xl font-semibold text-white mb-3">Ready for a transformation partnership?</h3><p className="text-white/60 text-sm mb-6 max-w-lg">This is our most committed engagement model. We only take on facilities where we believe we can deliver results. Let us assess the opportunity together.</p><Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Discuss a Partnership <ArrowRight size={14} /></Link></div></div></section>
      <PartnerCTA />
    </main>
  );
}
