// ─── Common healthcare roles by cadre ───
// Used in salary survey, work history, and mandate forms
// Ordered by seniority (junior to senior)

export const ROLES_BY_CADRE: Record<string, string[]> = {
  MEDICINE: [
    "House Officer",
    "Medical Officer",
    "Registrar",
    "Senior Registrar",
    "Consultant",
    "Senior Consultant",
    "Head of Department",
    "Chief Medical Director / CMD",
    "Locum Doctor",
  ],
  DENTISTRY: [
    "House Officer (Dental)",
    "Dental Officer",
    "Registrar (Dental)",
    "Senior Registrar (Dental)",
    "Consultant (Dental)",
    "Head of Department",
    "Dental Therapist",
    "Dental Technologist",
    "Dental Hygienist",
  ],
  NURSING: [
    "Staff Nurse / Nursing Officer I",
    "Nursing Officer II",
    "Senior Nursing Officer",
    "Principal Nursing Officer",
    "Assistant Chief Nursing Officer",
    "Chief Nursing Officer",
    "Deputy Director of Nursing",
    "Director of Nursing",
    "Locum Nurse",
  ],
  MIDWIFERY: [
    "Midwife",
    "Senior Midwife",
    "Principal Midwife",
    "Chief Midwife",
    "Deputy Director of Midwifery",
    "Director of Midwifery",
  ],
  PHARMACY: [
    "Intern Pharmacist",
    "Pharmacist Grade I",
    "Pharmacist Grade II",
    "Senior Pharmacist",
    "Principal Pharmacist",
    "Assistant Chief Pharmacist",
    "Chief Pharmacist",
    "Director of Pharmacy",
    "Locum Pharmacist",
    "Community Pharmacist",
    "Hospital Pharmacist",
  ],
  MEDICAL_LABORATORY_SCIENCE: [
    "Lab Scientist I",
    "Lab Scientist II",
    "Senior Lab Scientist",
    "Principal Lab Scientist",
    "Chief Lab Scientist",
    "Director of Lab Services",
    "Lab Technician",
  ],
  RADIOGRAPHY_IMAGING: [
    "Radiographer I",
    "Radiographer II",
    "Senior Radiographer",
    "Principal Radiographer",
    "Chief Radiographer",
    "Sonographer",
    "CT/MRI Technologist",
  ],
  REHABILITATION_THERAPY: [
    "Physiotherapist I",
    "Physiotherapist II",
    "Senior Physiotherapist",
    "Principal Physiotherapist",
    "Chief Physiotherapist",
    "Occupational Therapist",
    "Speech Therapist",
    "Audiologist",
  ],
  OPTOMETRY: [
    "Optometrist I",
    "Optometrist II",
    "Senior Optometrist",
    "Principal Optometrist",
    "Chief Optometrist",
    "Dispensing Optician",
  ],
  COMMUNITY_HEALTH: [
    "Junior CHEW",
    "Community Health Extension Worker (CHEW)",
    "Senior CHEW",
    "Community Health Officer (CHO)",
    "Principal CHO",
  ],
  ENVIRONMENTAL_HEALTH: [
    "Environmental Health Officer I",
    "Environmental Health Officer II",
    "Senior Environmental Health Officer",
    "Principal Environmental Health Officer",
    "Chief Environmental Health Officer",
    "Sanitary Inspector",
  ],
  NUTRITION_DIETETICS: [
    "Dietitian I",
    "Dietitian II",
    "Senior Dietitian",
    "Principal Dietitian",
    "Chief Dietitian",
    "Nutritionist",
  ],
  PSYCHOLOGY_SOCIAL_WORK: [
    "Clinical Psychologist",
    "Counselling Psychologist",
    "Senior Psychologist",
    "Medical Social Worker",
    "Senior Medical Social Worker",
    "Principal Medical Social Worker",
  ],
  PUBLIC_HEALTH: [
    "Public Health Officer",
    "Epidemiologist",
    "Health Educator",
    "M&E Officer",
    "Biostatistician",
    "Health Economist",
    "Programme Manager",
    "Director of Public Health",
  ],
  HEALTH_ADMINISTRATION: [
    "Health Records Officer",
    "Senior Health Records Officer",
    "Hospital Administrator",
    "Quality Manager",
    "HMO Officer",
    "Health Informatics Officer",
    "Medical Coder",
    "Director of Administration",
  ],
  BIOMEDICAL_ENGINEERING: [
    "Biomedical Engineer I",
    "Biomedical Engineer II",
    "Senior Biomedical Engineer",
    "Chief Biomedical Engineer",
    "Clinical Engineer",
    "Medical Equipment Technician",
  ],
};

// Flat list of all roles (for general search)
export const ALL_ROLES = Array.from(
  new Set(Object.values(ROLES_BY_CADRE).flat())
).sort();

export function getRolesForCadre(cadre: string): string[] {
  return ROLES_BY_CADRE[cadre] || ALL_ROLES;
}
