-- The Office of the Founding Partner runs the firm in a chief of staff way, so
-- it needs more than a queue of work handed to it: the promises people made,
-- the decisions waiting on one desk, and the cadence that repeats.

-- CreateEnum
CREATE TYPE "CommitmentStatus" AS ENUM ('OPEN', 'CHASED', 'HONOURED', 'MISSED', 'DROPPED');

-- CreateEnum
CREATE TYPE "DecisionStatus" AS ENUM ('PENDING', 'DECIDED', 'DEFERRED', 'DECLINED');

-- CreateEnum
CREATE TYPE "RecurrenceCadence" AS ENUM ('WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL');

-- CreateTable
CREATE TABLE "RecurringTask" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "brief" TEXT NOT NULL,
    "definitionOfDone" TEXT NOT NULL,
    "assigneeId" TEXT NOT NULL,
    "assignerId" TEXT NOT NULL,
    "cadence" "RecurrenceCadence" NOT NULL,
    "dayOfWeek" INTEGER,
    "dayOfMonth" INTEGER,
    "monthOfYear" INTEGER,
    "leadTimeDays" INTEGER NOT NULL DEFAULT 0,
    "checkInOffsetDays" INTEGER,
    "estimatedMinutes" INTEGER,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "lastGeneratedFor" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RecurringTask_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Commitment" (
    "id" TEXT NOT NULL,
    "what" TEXT NOT NULL,
    "owedByUserId" TEXT,
    "owedByName" TEXT,
    "owedByEmail" TEXT,
    "owedToUserId" TEXT,
    "dueDate" TIMESTAMP(3),
    "status" "CommitmentStatus" NOT NULL DEFAULT 'OPEN',
    "sourceType" TEXT,
    "sourceId" TEXT,
    "meetingId" TEXT,
    "lastChasedAt" TIMESTAMP(3),
    "chaseCount" INTEGER NOT NULL DEFAULT 0,
    "nextChaseAt" TIMESTAMP(3),
    "closedAt" TIMESTAMP(3),
    "note" TEXT,
    "recordedById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Commitment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Decision" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "background" TEXT NOT NULL,
    "options" TEXT[],
    "recommendation" TEXT NOT NULL,
    "costOfDelay" TEXT,
    "dueBy" TIMESTAMP(3),
    "status" "DecisionStatus" NOT NULL DEFAULT 'PENDING',
    "outcome" TEXT,
    "decidedAt" TIMESTAMP(3),
    "decidedById" TEXT,
    "forUserId" TEXT NOT NULL,
    "raisedById" TEXT NOT NULL,
    "linkedEntityType" TEXT,
    "linkedEntityId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Decision_pkey" PRIMARY KEY ("id")
);

-- AlterTable: tasks generated by the rhythm point back at it
ALTER TABLE "Task" ADD COLUMN "recurringTaskId" TEXT;

-- CreateIndex
CREATE INDEX "RecurringTask_active_cadence_idx" ON "RecurringTask"("active", "cadence");
CREATE INDEX "RecurringTask_assigneeId_idx" ON "RecurringTask"("assigneeId");
CREATE INDEX "Commitment_status_dueDate_idx" ON "Commitment"("status", "dueDate");
CREATE INDEX "Commitment_owedByUserId_status_idx" ON "Commitment"("owedByUserId", "status");
CREATE INDEX "Commitment_owedToUserId_status_idx" ON "Commitment"("owedToUserId", "status");
CREATE INDEX "Commitment_nextChaseAt_idx" ON "Commitment"("nextChaseAt");
CREATE INDEX "Commitment_meetingId_idx" ON "Commitment"("meetingId");
CREATE INDEX "Decision_forUserId_status_idx" ON "Decision"("forUserId", "status");
CREATE INDEX "Decision_status_dueBy_idx" ON "Decision"("status", "dueBy");
CREATE INDEX "Decision_raisedById_idx" ON "Decision"("raisedById");
CREATE INDEX "Task_recurringTaskId_idx" ON "Task"("recurringTaskId");

-- AddForeignKey
ALTER TABLE "RecurringTask" ADD CONSTRAINT "RecurringTask_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RecurringTask" ADD CONSTRAINT "RecurringTask_assignerId_fkey" FOREIGN KEY ("assignerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Commitment" ADD CONSTRAINT "Commitment_owedByUserId_fkey" FOREIGN KEY ("owedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Commitment" ADD CONSTRAINT "Commitment_owedToUserId_fkey" FOREIGN KEY ("owedToUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Commitment" ADD CONSTRAINT "Commitment_recordedById_fkey" FOREIGN KEY ("recordedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Commitment" ADD CONSTRAINT "Commitment_meetingId_fkey" FOREIGN KEY ("meetingId") REFERENCES "Meeting"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Decision" ADD CONSTRAINT "Decision_forUserId_fkey" FOREIGN KEY ("forUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Decision" ADD CONSTRAINT "Decision_raisedById_fkey" FOREIGN KEY ("raisedById") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Decision" ADD CONSTRAINT "Decision_decidedById_fkey" FOREIGN KEY ("decidedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Task" ADD CONSTRAINT "Task_recurringTaskId_fkey" FOREIGN KEY ("recurringTaskId") REFERENCES "RecurringTask"("id") ON DELETE SET NULL ON UPDATE CASCADE;
