#!/usr/bin/env python3
"""
Compare MWAN list against everything currently in the CadreProfessional DB.

Reads:
  /Users/debo/Downloads/MWAN List.xlsx (256 rows, schema: S/N, Full Name, Phone Number, Email, Specialty, Organization)
  /tmp/cadre_existing.csv (snapshot of all CadreProfessional rows: name, email, phone)

The snapshot is generated by the companion .ts script before this runs,
because Python can't talk to Prisma directly.

Outputs:
  /tmp/mwan_duplicates_strong.csv  -> email or phone match (drop)
  /tmp/mwan_duplicates_name.csv    -> exact/fuzzy name only (human review)
  /tmp/mwan_unique_new.csv         -> candidates to import
"""
import csv
import re
import sys
from difflib import SequenceMatcher

import openpyxl

NEW = "/Users/debo/Downloads/MWAN List.xlsx"
EXISTING = "/tmp/cadre_existing.csv"
OUT_STRONG = "/tmp/mwan_duplicates_strong.csv"
OUT_NAME = "/tmp/mwan_duplicates_name.csv"
OUT_UNIQUE = "/tmp/mwan_unique_new.csv"


def norm_email(e):
    if not e:
        return ""
    return str(e).strip().lower().replace("\xa0", "").replace(" ", "")


def norm_phone(p):
    if not p:
        return ""
    d = re.sub(r"\D", "", str(p))
    if d.startswith("234"):
        d = d[3:]
    if d.startswith("0"):
        d = d[1:]
    if len(d) < 9:
        return ""
    return d[-10:]


def norm_name(n):
    if not n:
        return ""
    s = str(n).strip().lower()
    s = re.sub(r"^(prof\.?|dr\.?|doctor|mrs\.?|ms\.?|mr\.?)\s+", "", s)
    s = re.sub(r"^(prof\.?|dr\.?|doctor|mrs\.?|ms\.?|mr\.?)\s+", "", s)
    s = re.sub(r"[^\w\s]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def name_tokens(n):
    return set(norm_name(n).split())


# Load existing
existing_rows = list(csv.DictReader(open(EXISTING)))
print(f"Existing CadreProfessional records: {len(existing_rows)}")

email_idx, phone_idx, name_idx = {}, {}, {}
name_token_list = []

for r in existing_rows:
    e = norm_email(r.get("email"))
    p = norm_phone(r.get("phone"))
    fullname = ((r.get("firstName") or "") + " " + (r.get("lastName") or "")).strip()
    n = norm_name(fullname)
    if e:
        email_idx.setdefault(e, []).append(r)
    if p:
        phone_idx.setdefault(p, []).append(r)
    if n:
        name_idx.setdefault(n, []).append(r)
        name_token_list.append((name_tokens(fullname), n, r))

# Load MWAN
wb = openpyxl.load_workbook(NEW, data_only=True)
ws = wb.active
headers = None
mwan_rows = []
for row in ws.iter_rows(values_only=True):
    if headers is None:
        headers = [str(c).strip() if c else "" for c in row]
        continue
    if all(c is None for c in row):
        continue
    rec = dict(zip(headers, row))
    mwan_rows.append(rec)

print(f"MWAN rows: {len(mwan_rows)}")

# Match
strong_dupes, name_dupes, unique_new = [], [], []

for r in mwan_rows:
    name = r.get("Full Name") or ""
    email = r.get("Email") or ""
    phone = r.get("Phone Number") or ""
    org = r.get("Organization") or ""
    spec = r.get("Specialty") or ""

    e = norm_email(email)
    p = norm_phone(phone)
    n = norm_name(name)

    matches = []
    match_type = []
    if e and e in email_idx:
        matches.extend(email_idx[e]); match_type.append("email")
    if p and p in phone_idx:
        matches.extend(phone_idx[p]); match_type.append("phone")

    if matches:
        ex = matches[0]
        strong_dupes.append({
            "match_type": "+".join(match_type),
            "new_name": name, "new_email": email, "new_phone": phone,
            "new_org": org, "new_specialty": spec,
            "existing_name": f"{ex.get('firstName','')} {ex.get('lastName','')}".strip(),
            "existing_email": ex.get("email", ""),
            "existing_phone": ex.get("phone", ""),
            "existing_specialty": ex.get("subSpecialty", ""),
            "existing_facility": ex.get("currentFacility", ""),
        })
        continue

    if n and n in name_idx:
        ex = name_idx[n][0]
        name_dupes.append({
            "match_type": "exact_name", "score": 1.0,
            "new_name": name, "new_email": email, "new_phone": phone,
            "new_org": org, "new_specialty": spec,
            "existing_name": f"{ex.get('firstName','')} {ex.get('lastName','')}".strip(),
            "existing_email": ex.get("email", ""),
            "existing_phone": ex.get("phone", ""),
            "existing_specialty": ex.get("subSpecialty", ""),
            "existing_facility": ex.get("currentFacility", ""),
        })
        continue

    # Fuzzy
    if n:
        toks = name_tokens(name)
        best, best_score = None, 0.0
        for etoks, en, er in name_token_list:
            if not etoks or not toks:
                continue
            shared = {t for t in (toks & etoks) if len(t) >= 3}
            if len(shared) < 2:
                continue
            jac = len(toks & etoks) / len(toks | etoks)
            if jac < 0.6:
                continue
            seq = SequenceMatcher(None, n, en).ratio()
            score = 0.5 * jac + 0.5 * seq
            if score > best_score:
                best_score = score; best = er
        if best and best_score >= 0.85:
            name_dupes.append({
                "match_type": "fuzzy_name", "score": round(best_score, 3),
                "new_name": name, "new_email": email, "new_phone": phone,
                "new_org": org, "new_specialty": spec,
                "existing_name": f"{best.get('firstName','')} {best.get('lastName','')}".strip(),
                "existing_email": best.get("email", ""),
                "existing_phone": best.get("phone", ""),
                "existing_specialty": best.get("subSpecialty", ""),
                "existing_facility": best.get("currentFacility", ""),
            })
            continue

    unique_new.append({
        "name": name, "email": email, "phone": phone,
        "place": org, "specialty": spec, "sheet": "MWAN",
    })


def write_csv(path, rows, fields):
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)


write_csv(OUT_STRONG, strong_dupes,
          ["match_type", "new_name", "new_email", "new_phone", "new_org", "new_specialty",
           "existing_name", "existing_email", "existing_phone", "existing_specialty", "existing_facility"])
write_csv(OUT_NAME, name_dupes,
          ["match_type", "score", "new_name", "new_email", "new_phone", "new_org", "new_specialty",
           "existing_name", "existing_email", "existing_phone", "existing_specialty", "existing_facility"])
write_csv(OUT_UNIQUE, unique_new,
          ["name", "email", "phone", "place", "specialty", "sheet"])

print()
print(f"STRONG dupes (email or phone match):  {len(strong_dupes):4d}  -> {OUT_STRONG}")
print(f"NAME dupes (exact or fuzzy name):     {len(name_dupes):4d}  -> {OUT_NAME}")
print(f"UNIQUE new (candidates to import):    {len(unique_new):4d}  -> {OUT_UNIQUE}")
