import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import PartnerCTA from "@/components/cfa/PartnerCTA";

export const metadata: Metadata = { title: "Health Systems & Public Sector Advisory | Consult For Africa", description: "C4A supports governments, development partners, and NGOs on health system design, hospital network planning, and policy-to-implementation across Africa.", openGraph: { title: "Health Systems & Public Sector Advisory | Consult For Africa", description: "Health system design, hospital network planning, and policy-to-implementation across Africa.", type: "website", images: ["/og-image.jpg"] } };

const indicators = ["Health system reform mandates without implementation capacity", "Hospital network planning without operational expertise", "Policy designed in isolation from delivery reality", "PHC systems underperforming despite investment", "Development partner programmes without local execution capability", "Cross-border health corridor planning needs"];
const phases = [
  { num: "01", name: "System Mapping & Stakeholder Analysis", weeks: "Weeks 1 to 6", desc: "Map the health system landscape, identify stakeholders, understand political economy, and define the scope of intervention.", deliverables: ["Health system mapping report", "Stakeholder analysis", "Intervention scope document"] },
  { num: "02", name: "Strategy & Framework Design", weeks: "Weeks 6 to 14", desc: "Design the policy framework, hospital network plan, or programme strategy with full stakeholder alignment.", deliverables: ["Policy framework document", "Hospital network master plan", "Implementation roadmap"] },
  { num: "03", name: "Implementation Support", weeks: "Months 4 to 12", desc: "Embed implementation support within government or partner structures. Technical assistance, capacity building, and performance monitoring.", deliverables: ["Technical assistance deployment", "Capacity building programme", "Progress dashboards"] },
  { num: "04", name: "Monitoring & Evaluation", weeks: "Months 12 to 24", desc: "Establish M&E frameworks, conduct impact assessments, and build local capacity for ongoing system stewardship.", deliverables: ["M&E framework", "Impact assessment report", "Sustainability transition plan"] },
];
const outcomes = [{ value: "12", label: "Health system advisory mandates completed" }, { value: "5", label: "National-level hospital network plans delivered" }, { value: "3", label: "Cross-border health corridor frameworks" }, { value: "100%", label: "Stakeholder alignment on delivery milestones" }];
const qualifies = ["Ministries of health undertaking system reform", "Development partners (WHO, World Bank, AfDB, USAID)", "NGOs implementing health programmes at scale", "State governments strengthening primary healthcare", "Regional bodies planning cross-border health systems"];

export default function HealthSystemsPage() {
  return (
    <main>
      <section className="relative overflow-hidden text-white" style={{ paddingTop: "5rem", minHeight: "60svh" }}><div className="absolute inset-0" style={{ background: "#06090f" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 70% 80% at 80% 40%, rgba(20,130,200,0.15) 0%, rgba(12,70,130,0.06) 55%, transparent 70%)" }} /><div className="absolute inset-0 pointer-events-none" style={{ background: "radial-gradient(ellipse 40% 50% at 20% 10%, rgba(201,168,76,0.1) 0%, transparent 60%)" }} /><div className="absolute inset-0 pointer-events-none opacity-[0.036]" style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`, backgroundSize: "180px" }} />
        <div className="relative max-w-7xl mx-auto px-6 py-24 md:py-32">
          <p className="mb-6 text-xs font-medium uppercase tracking-[0.22em]" style={{ color: "#D4AF37" }}>CFA Service</p>
          <h1 className="font-semibold leading-[1.1] tracking-tight text-white max-w-3xl" style={{ fontSize: "clamp(2rem, 5vw, 3.5rem)" }}>Health Systems<br /><span style={{ color: "rgba(255,255,255,0.65)" }}>& Public Sector Advisory</span></h1>
          <div className="mt-6 w-12 h-[2px]" style={{ background: "#D4AF37" }} />
          <p className="mt-6 max-w-2xl leading-relaxed" style={{ fontSize: "clamp(1rem,1.5vw,1.1rem)", color: "rgba(255,255,255,0.65)" }}>We support governments, development partners, and NGOs on health system design, hospital network planning, and policy-to-implementation programmes across African markets.</p>
          <div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Start a Conversation <ArrowRight size={15} /></Link><Link href="/services" className="inline-flex items-center gap-2 px-7 py-3.5 rounded-xl font-semibold text-sm" style={{ border: "1px solid rgba(255,255,255,0.18)", color: "rgba(255,255,255,0.8)" }}>All Services</Link></div>
        </div>
      </section>
      <section className="py-16" style={{ background: "linear-gradient(135deg, #0B3C5D 0%, #0e4a75 100%)" }}><div className="max-w-4xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-5">{outcomes.map((o) => (<div key={o.value} className="glass-card p-6 text-center"><p className="text-2xl font-bold text-white mb-1">{o.value}</p><p className="text-white/60 text-xs leading-snug">{o.label}</p></div>))}</div></section>
      <section className="py-20 px-6" style={{ background: "#F8FAFC" }}><div className="max-w-5xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-[#0B3C5D]/50 mb-3">Indicators</p><h2 className="text-2xl md:text-3xl font-semibold text-gray-900 mb-4">Is Your Health System Programme Stalling?</h2><p className="text-gray-500 text-sm max-w-xl mb-12">Policy without implementation is just a document. These signs suggest you need operational advisory.</p><div className="grid sm:grid-cols-2 gap-3">{indicators.map((s) => (<div key={s} className="flex items-center gap-3 p-4 rounded-xl" style={{ background: "#fff", border: "1px solid #e5eaf0" }}><span className="w-5 h-5 rounded-full flex items-center justify-center shrink-0 text-xs" style={{ background: "#FEF3C7", color: "#D97706" }}>!</span><span className="text-sm text-gray-700">{s}</span></div>))}</div></div></section>
      <section className="py-24 px-6" style={{ background: "linear-gradient(145deg, #0a1e32 0%, #112e4a 100%)" }}><div className="max-w-5xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-white/50 mb-3">Engagement Structure</p><h2 className="text-2xl md:text-3xl font-semibold text-white mb-14">How a Health Systems Engagement Works</h2><div className="space-y-5">{phases.map((phase) => (<div key={phase.num} className="glass-card p-7 grid md:grid-cols-[200px_1fr] gap-6"><div><div className="inline-flex items-center justify-center w-10 h-10 rounded-full text-xs font-bold mb-3" style={{ background: "rgba(212,175,55,0.12)", border: "1px solid rgba(212,175,55,0.35)", color: "#D4AF37" }}>{phase.num}</div><p className="font-semibold text-white text-base mb-1">{phase.name}</p><p className="text-xs" style={{ color: "#D4AF37" }}>{phase.weeks}</p></div><div><p className="text-white/70 text-sm leading-relaxed mb-4">{phase.desc}</p><div className="flex flex-wrap gap-2">{phase.deliverables.map((d) => (<span key={d} className="px-3 py-1 rounded-full text-xs" style={{ background: "rgba(255,255,255,0.07)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.1)" }}>{d}</span>))}</div></div></div>))}</div></div></section>
      <section className="py-20 px-6" style={{ background: "#ffffff" }}><div className="max-w-4xl mx-auto"><p className="uppercase tracking-[0.2em] text-xs text-[#0B3C5D]/50 mb-3">Who This Is For</p><h2 className="text-2xl md:text-3xl font-semibold text-gray-900 mb-10">The Institutions We Serve</h2><div className="space-y-3">{qualifies.map((q) => (<div key={q} className="flex items-center gap-4 p-4 rounded-xl" style={{ border: "1px solid #e5eaf0" }}><div className="w-2 h-2 rounded-full shrink-0" style={{ background: "#D4AF37" }} /><span className="text-sm text-gray-700">{q}</span></div>))}</div><div className="mt-12 rounded-2xl p-8" style={{ background: "#0F2744" }}><p className="text-xs font-semibold uppercase tracking-[0.15em] mb-2" style={{ color: "#D4AF37" }}>Start with a Conversation</p><h3 className="text-xl font-semibold text-white mb-3">Planning a health system intervention?</h3><p className="text-white/60 text-sm mb-6 max-w-lg">We bring operational depth to policy work. Let us understand your mandate and show you where we can add value.</p><Link href="/contact" className="inline-flex items-center gap-2 px-6 py-3 rounded-xl font-semibold text-sm" style={{ background: "#D4AF37", color: "#0F2744" }}>Discuss Your Programme <ArrowRight size={14} /></Link></div></div></section>
      <PartnerCTA />
    </main>
  );
}
